name: ci
on: pull_request
jobs:
  build:
    name: Lint, Test, & Build
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v1
          with:
            node-version: '12'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
        env:
          CI: true
      - run: yarn build
