export enum ChromeRuntimeMessages {
  ENABLE_POPUP_INTERACTION = 'ENABLE_POPUP_INTERACTION',
  DISABLE_POPUP_INTERACTION = 'DISABLE_POPUP_INTERACTION',
  GET_PARTY_DETAILS = 'GET_PARTY_DETAILS',
  SET_PARTY_DETAILS = 'SET_PARTY_DETAILS',
  JOIN_PARTY = 'JOIN_PARTY',
  URL_CHANGE = 'URL_CHANGE',
  GET_USER_DETAILS = 'GET_USER_DETAILS',
  SET_USER_DETAILS = 'SET_USER_DETAILS',
  ADD_NOTIFICATION = 'ADD_NOTIFICATION',
}
