export enum ChromeRuntimeMessages {
  HIDE_CONTENT_SCRIPT_HTML = 'HIDE_CONTENT_SCRIPT_HTML',
  TOGGLE_CHAT = 'TOGGLE_CHAT',
  ENABLE_POPUP_INTERACTION = 'ENABLE_POPUP_INTERACTION',
  DISABLE_POPUP_INTERACTION = 'DISABLE_POPUP_INTERACTION',
  GET_PARTY_DETAILS = 'GET_PARTY_DETAILS',
  SET_PARTY_DETAILS = 'SET_PARTY_DETAILS',
  JOIN_PARTY = 'JOIN_PARTY',
  URL_CHANGE = 'URL_CHANGE',
}
