export enum PartyActions {
  JOIN_PARTY = 'JOIN_PARTY',
  LEAVE_PARTY = 'LEAVE_PARTY',
  SET_PARTY = 'SET_PARTY',
  ADD_USER = 'ADD_USER',
  REMOVE_USER = 'REMOVE_USER',
  SET_IS_HOST = 'SET_IS_HOST',
}
