export enum PartyActions {
  JOIN_PARTY = 'JOIN_PARTY',
  LEAVE_PARTY = 'LEAVE_PARTY',
  SET_PARTY = 'SET_PARTY',
  ADD_USER = 'ADD_USER',
  UPDATE_USER = 'UPDATE_USER',
  REMOVE_USER = 'REMOVE_USER',
  HOST_NAV = 'HOST_NAV',
  SET_IS_HOST = 'SET_IS_HOST',
  CREATE_NOTIFICATION = 'CREATE_NOTIFICATION',
  MARK_NOTIFICATION_SEEN = 'MARK_NOTIFICATION_SEEN',
}
