export enum PartyActions {
  JOIN_PARTY = 'JOIN_PARTY',
  CREATE_PARTY = 'CREATE_PARTY',
  LEAVE_PARTY = 'LEAVE_PARTY',
  SET_PARTY_ID = 'SET_PARTY_ID',
  SET_JOIN_URL = 'SET_JOIN_URL',
  SET_HOST = 'SET_HOST',
}
