name: ci
on: [push, pull_request]
jobs:
  build:
    name: Lint, Test, & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn tsc
      - run: yarn test
        env:
          CI: true
      - run: yarn build
  publish:
    name: Publish to Chrome Web Store
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'release')
    steps:
      - run: zip -vr build.zip build/ -x "*.DS_Store"
      - uses: rkrishn7/chrome-extension-upload-action@1.41
        with:
          refresh-token: ${{ secrets.CHROME_WS_REFRESH_TOKEN }}
          client-id: ${{ secrets.CHROME_WS_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_WS_CLIENT_SECRET }}
          file-name: './build.zip'
          app-id: ${{ secrets.CHROME_WS_APP_ID }}
          publish: true
